### PR TITLE
GS1 datamatrix support

### PR DESCRIPTION
**Pull request by nemik**
This PR adds support for a "gs1datamatrix" field type and some validation checks for it.

### CODE REVIEW

**Comment by hand-dot** [comment]
Hi @nemik ,
To accept this PR, We need changes for UI .

**Comment by nemik** [comment]
Thanks for the reply. I've added some tests as well as a preview PNG like the others for the UI. But if there is something else I'm missing let me know.

**Comment by hand-dot** [comment]
Hey @nemik ,
Released!
Thank you for your contribution to pdfme.
Also, thanks for your  sponsorship.

**Comment by nemik** [comment]
Thank you for making this amazing project!

**Pull request merged**
