### PR TITLE
Exposed page cursor from Designer

### PR DESCRIPTION
**Pull request by hlin-neo4j**
Thought it might be helpful to be to add an api to the Designer to get the current page.

### CODE REVIEW

**Comment by hand-dot** [comment]
Hey @hlin-neo4j ! Thank you for creating PR!

I've checked the code and behavior; it looks good. 
However, I don't quite understand the use case.

The same goes for the issue below.
https://github.com/pdfme/pdfme/issues/442

Could you explain a bit more why we should add this feature?

**Comment by hlin-neo4j** [comment]
Ah I didn't see the #442 issue, but it sounds like there's at least two of us that needs it. For my use case, I have an external component (a sidebar) that displays and tracks the Schemas on the Designer. I store metadata about the Schemas as well, and all of this is stored in my application's Redux. I have users interact with this external Sidebar, so it is calling designer.current.updateTemplate, getTemplate, etc to make changes to the Designer. Now when the user creates multiple pages and scrolls between them, my Sidebar does not get any events that say a different page is displayed. designer.getTemplate is the only call that I know of that gives back information of the Template Schemas, but there is no "currentPage."

**Comment by hand-dot** [comment]
@hlin-neo4j 
Thank you, I understand. 
This feature is very effective, so I want to release it soon. 

Could you switch the base branch to main? 🙏

**Comment by hlin-neo4j** [comment]
@hand-dot I can pull back this pull request and make a new one off of base branch if that works for you

**Comment by hand-dot** [comment]
Can you make new PR?🙇‍♂️

**Comment by hlin-neo4j** [comment]
@hand-dot Just created #446

**Comment by hand-dot** [comment]
Thank you, I'll handle in https://github.com/pdfme/pdfme/pull/446

**Pull request closed without merging**
