### PR TITLE
Rotate Refactor

### PR DESCRIPTION
**Pull request by peteward**
Re-implementation of [Rotate PR](https://github.com/pdfme/pdfme/pull/277)

UI
Screenshot 2023-10-21 at 12 09 42
PDF
Screenshot 2023-10-21 at 12 10 18

TODO:
- [x] Confirm all permutations of text layout
- [x] Existing tests fixed
- [x] New unit tests added 
- [x] New Integration tests added

### CODE REVIEW

**Comment by peteward** [comment]
Text rotation looking good with various style permutations:

Screenshot 2023-10-21 at 12 23 05

Screenshot 2023-10-21 at 12 23 23

There is an issue where you may not be able to place a rotated element in the desired position due to UI limitations of x and y must be > 0, but this can be looked at separately to decide how much of an issue it is and whether to resolve.

**Comment by hand-dot** [comment]
Okay, we should handle as another issues about this issue.

**Comment by peteward** [comment]
only integration tests remain to be added. I will do this tomorrow.
If this PR is blocking you @hand-dot then I think you can review then merge and I can add the extra tests afterwards.

**Review by hand-dot — APPROVED** [review]
Looks good!

**Comment by hand-dot** [comment]
@peteward 
I've reviewed it! Thank you as always.

This PR is not currently blocking me, so feel free to merge it whenever you like!

**Comment by hand-dot** [comment]
Cooooooool!

**Pull request merged**
