### PR TITLE
Adds automated publishing workflow to NPM

### PR DESCRIPTION
**Pull request by dkastl**
This pull request introduces an automated publishing workflow to NPM for the multiple packages included in this repository.

The motivation behind this PR is to simplify the use of the multiple NPM packages in this repository through NPM. In the release documentation it seemed to me that the publishing process so far was manual, and I thought automation will allow publishing of NPM packages more frequently.

The publishing process is triggered by creating a Git tag and it distinguishs between stable releases and pre-releases by publishing to different NPM channels. 
Additionally, the CI creates releases to the `dev` channel on NPM for every commit to the main branch, so it's easy to stay up-to-date with the latest development.

I tested the workflow successfully until the actual publishing to NPM, which requires to configure a NPM Authentication Token name `NPM_TOKEN` as Github secret.

### CODE REVIEW

**Comment by hand-dot** [comment]
@peteward 
I'd like to know your opinion

**Comment by hand-dot** [comment]
I used to update manually, but it seems good that with this script, development releases can be obtained automatically from the main branch.

I would like to adopt this operation as it seems better.

**Comment by peteward** [comment]
sorry for the late reply.

Releases are your area @hand-dot, so if you are happy with the process then great.

Thank you very much @dkastl for the contribution! 👍

**Comment by hand-dot** [comment]
@dkastl 

I'm currently trying to release V3 using this workflow, but it fails with an error. The cause of the error seems to be that the new value is not set correctly with npm version, and it tries to publish with a duplicate version, which prevents the publish from happening.

If you have any ideas for a fix, I'd like to hear them.

https://github.com/pdfme/pdfme/actions/runs/6742936403

**Comment by hand-dot** [comment]
I'm sorry. I didn't understand how to use it.

It seems that 3.0.0-beta.2 already existed, so it was necessary to create the tag from 3.0.1 onwards.

**Comment by dkastl** [comment]
Sorry, I was not connected to internet today, but I will take a look tomorrow. I'm not sure if NPM requires increasing version numbers for example. It's the part I wasn't able to test properly because changing the NPM organisation causes other issues.

**Comment by dkastl** [comment]
It took me a bit longer to take a look, but checking the GH Actions and published NPM packages it seems to working now, right?

Thanks a lot for merging! This makes is a lot easier to stay up-to-date with the latest state of development!

**Comment by hand-dot** [comment]
@dkastl Thank you👍

**Pull request merged**
