### PR TITLE
Dynamic table schema issue fixes

### PR DESCRIPTION
**Pull request by vpn-dev**

### CODE REVIEW

**Comment by hand-dot** [comment]
I found another problem.

CleanShot 2024-09-03 at 17 32 14

**Comment by hand-dot** [comment]
I believe that the [PR](https://github.com/pdfme/pdfme/pull/574) I'm currently working on is likely to fix the issue correctly without introducing any regressions.

**Comment by vpn-dev** [comment]
> I found another problem.
> 
> CleanShot 2024-09-03 at 17 32 14 [ CleanShot 2024-09-03 at 17 32 14 ](https://private-user-images.githubusercontent.com/24843808/363903862-a163be9a-bfed-4279-b43b-eb4d3ba3359b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNTYxNzgsIm5iZiI6MTcyNTM1NTg3OCwicGF0aCI6Ii8yNDg0MzgwOC8zNjM5MDM4NjItYTE2M2JlOWEtYmZlZC00Mjc5LWI0M2ItZWI0ZDNiYTMzNTliLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDA5MzExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4ZDEyMWY2OGI0OTdiMWY3ZWI3ZmRjOTE3ZTMzMzA2NTY1NWE2ZTNiYzY1NTI1NjhjOGJjMGRjYzk5OWU4MzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ni0xvYtAe9BpIS6Jjod28OPkfC7tThJUeIK9y5JBq6s) [ ](https://private-user-images.githubusercontent.com/24843808/363903862-a163be9a-bfed-4279-b43b-eb4d3ba3359b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNTYxNzgsIm5iZiI6MTcyNTM1NTg3OCwicGF0aCI6Ii8yNDg0MzgwOC8zNjM5MDM4NjItYTE2M2JlOWEtYmZlZC00Mjc5LWI0M2ItZWI0ZDNiYTMzNTliLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDA5MzExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4ZDEyMWY2OGI0OTdiMWY3ZWI3ZmRjOTE3ZTMzMzA2NTY1NWE2ZTNiYzY1NTI1NjhjOGJjMGRjYzk5OWU4MzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ni0xvYtAe9BpIS6Jjod28OPkfC7tThJUeIK9y5JBq6s)

is this existing issue, or regression because of my pr

**Comment by hand-dot** [comment]
Go to form viewer screen

**Pull request closed without merging**
