### PR TITLE
Reset rotation field when changing schema in UI

### PR DESCRIPTION
**Pull request by peteward**
Ref: https://github.com/pdfme/pdfme/issues/334

Opened on behalf of @LeandroBanaszeski

### CODE REVIEW

**Comment by hand-dot** [comment]
@peteward 
Thank you.

**Comment by peteward** [comment]
I think the issue here is due to setting form values [here](https://github.com/pdfme/pdfme/blob/main/packages/ui/src/components/Designer/Sidebar/DetailView/index.tsx#L60C1-L62).

We're setting the values for the widgets based on the active schema, but it's possible that the incoming data is missing a value (such as rotation, or a colour which can be unset) and so the previous stale value remains.

**Comment by peteward** [comment]
@hand-dot I think this solution is a bit more efficient and cleaner at the appropriate point. Let me know what you think.

**Comment by hand-dot** [comment]
LGTM!

**Review by hand-dot — APPROVED** [review]

**Comment by hand-dot** [comment]
@peteward 

Sorry, but when I debugged it again, it turns out this is causing a different issue.

 For example, if the position is changed by input entry in the Edit Field, the focus is lost. 
 Also, the validation for the min and max of rotate is not working.

**Pull request merged**
