### PR TITLE
german language supprot added

### PR DESCRIPTION
**Pull request by olga-krayevska**

### CODE REVIEW

**Review by hand-dot — COMMENTED** [review]
Hey @olga-krayevska 

I asked ChatGPT and want to confirm the following two points.

1.  'Left' should be 'Links'
2. 'Top' should be 'Oben'

Aren't the above more accurate for the German translation? 
If you did it intentionally, please tell me the reason.

The rest seems good. I want to merge if the above is confirmed!

Thank you for contributing!
I'm happy that users in Germany can use pdfme by your contribution.

**Comment by olga-krayevska** [comment]
> Hey @olga-krayevska
> 
> I asked ChatGPT and want to confirm the following two points.
> 
> 1. 'Left' should be 'Links'
> 2. 'Top' should be 'Oben'
> 
> Aren't the above more accurate for the German translation? If you did it intentionally, please tell me the reason.
> 
> The rest seems good. I want to merge if the above is confirmed!
> 
> Thank you for contributing! I'm happy that users in Germany can use pdfme by your contribution.

hello @hand-dot yes, you are right about Left and Top, I changed it and also changed  'schemas.center': 'Zentriert' (more appropriate translation)

**Review by hand-dot — APPROVED** [review]
Thank you for your contribution! 
We are brightening the future of PDF creation!

**Comment by hand-dot** [comment]
This changes will be published next release.

**Comment by olga-krayevska** [comment]
> Thank you for your contribution! We are brightening the future of PDF creation!

@hand-dot thank you for great lib and for reviewing my PR so quickly

**Pull request merged**
